# Generated by Django 2.2.19 on 2021-02-19 09:58

from django.db import migrations, models
import django_frontify.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontify_image', django_frontify.fields.FrontifyImageField(blank=True, verbose_name='Frontify Image')),
            ],
        ),
    ]
